services:
  # PROJECT 1 - PORTFOLIO
  portfolio:
    build:
      context: projects/hvkalayil.github.io
      dockerfile: Dockerfile
    ports:
      - "1000:80"
    restart: unless-stopped

  # PROJECT 2 - Learn.io
  learnio-frontend:
    build:
      context: projects/learn.io/apps/web
      dockerfile: Dockerfile
    ports:
      - "1001:8000"
    env_file:
      - projects/learn.io/.frontend.env
    restart: unless-stopped

  learnio-backend:
    build:
      context: projects/learn.io/apps/api
      dockerfile: Dockerfile
    ports:
      - "1002:4000"
    env_file:
      - projects/learn.io/.api.env
    restart: unless-stopped

  learnio-db:
    build:
      context: projects/learn.io/apps/db
      dockerfile: Dockerfile
    ports:
      - "1003:4001"
    env_file:
      - projects/learn.io/.db.env
    restart: unless-stopped

  # PROJECT 3 - Sens.ai
  sens.ai:
    build:
      context: projects/sens.ai-frontend
      dockerfile: Dockerfile
    ports:
      - "1004:80"
    env_file:
      - projects/sens.ai-frontend/.env
    restart: unless-stopped
